# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://randyor.github.io/
baseurl: /'/
title: Randy Or
author: Randy Or
description: Portfolio  
avatar: profile.png
email: ror@alumni.ubc.ca
github: randyor # username
twitter: randyderekor
linkedin: randyor
stackoverflow: users/4282698/randy-or #e.g: users/2735833/proton1h1

# needed for travis-ci build
exclude: [vendor]
